[build]
  publish = "."
  functions = "netlify/functions"

# Route /api/coach to the Netlify Function
[[redirects]]
  from = "/api/coach"
  to = "/.netlify/functions/coach"
  status = 200

# Optional security headers (safe defaults)
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
