# netlify.toml — Optional. Only use if you want stricter CSV handling now.
# If this file already exists in your repo, you can skip replacing it for now.
# You can come back later to add the CSV headers block safely.

# [[headers]]
#   for = "/data/*.csv"
#   [headers.values]
#     Content-Type = "text/csv; charset=utf-8"
#     Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
#     Pragma = "no-cache"
#     Expires = "0"
